name: preview

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EXPO_USE_FAST_RESOLVER: true # Use the faster Metro resolver in SDK 51

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v4

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 👷 Build packages
        run: pnpm run -w build:example

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          working-directory: apps/example
          command: eas update --auto --branch=pr-${{ github.event.number }}
          comment: false
